### ISSUE TITLE
@tacky need a logo

### ISSUE THREAD

**Issue by geoffgu** [kujiale/tacky#5]

**Comment by zuurw** [comment]
Hi, I can design a free logo/icon  for this project. If it's something you're interested in, please, let me know!

**Comment by geoffgu** [comment]
> Hi, I can design a free logo/icon for this project. If it's something you're interested in, please, let me know!

Thanks! I need your help. It would be better if there were some sense of technology.

**Comment by zuurw** [comment]
Hi @geoffgu , can you give me more informations about this project?

**Comment by geoffgu** [comment]
Hi @zuurw , this project is a front-end framework based on react. In the future, it will contain page router, state management framework, i18n, api call library, dev tool and so on.

**Comment by geoffgu** [comment]
@zuurw emmm... maybe a front-end development common solution, helping developer create a maintainable app in less time.

**Comment by zuurw** [comment]
Hi, I would like to know what do you want for this logo, can you give me something to get inspired?

Thank you!

Best Regards!

**Comment by geoffgu** [comment]
Different things, gather together, become a new meaningful things...maybe different graphics, but it compose a new graphic as a whole, or insert the 'T' character for this logo
